### ISSUE TITLE
Standings for Beer League

### ISSUE THREAD

**Issue by herotosucara** [majorbyte/rebbl#611]
Season 2: Start June 1st, 2020
5 Round Robin Divisions located in `REBBLL` league
Returning: `Ale` `Lager` - Top 2 in each go to playoffs
Fresh: `Stout` `Porter` `Pilsner` - Top 1 in each go to playoffs (1 wildcard for the best 2nd place team).

Season 1 if you want to try to tackle it:
2 Fresh Divs: `Ale` `Lager` - Swiss format
Ran from about February to mid May 7 fortnight rounds.
Top 4 of each went to playoffs.

Thanks!

**Comment by majorbyte** [comment]
Done
