### ISSUE TITLE
Season names are case-sensitive and stored mixed-case

### ISSUE THREAD

**Issue by cpennington** [majorbyte/rebbl#777]
At least for ReBBRL, the season names are stored in both upper and lower case, and the search is done case-sensitively. For example, https://rebbl.net/api/v2/division/ReBBRL%20College%20League/Season%2012/Season%2012%20-%20Division%20AM%20B/slim and https://rebbl.net/api/v2/division/ReBBRL%20College%20League/season%2012/Season%2012%20-%20Division%20AM%20B/slim return different results, and each only contains a subset of the games (or projected games) for the season.

**Comment by cpennington** [comment]
I looked at making a code change for this, and https://github.com/majorbyte/rebbl/blob/master/lib/DataService.js#L72 seemed like the relevant place where schedules were searched. However, https://docs.mongodb.com/manual/core/index-text/#case-insensitivity suggests that case insensitivity is a property of the text index, rather than the search, and I didn't see anything in the repo that was managing indexes via migrations or the like.

**Comment by majorbyte** [comment]
This was not so much about case sensitivity, but a misconfiguration of rebbl.net
